#!/bin/bash

make clean RTAI=0 XFORMS=1 NAS=0 HARD_RT=0 MSG_PRINT=1 ETHERNET=1 EXTRA_CFLAGS="-O0 -ggdb" DEBUG=1 -j4
make lte-softmodem RTAI=0 XFORMS=1 NAS=0 HARD_RT=0 MSG_PRINT=1 ETHERNET=1 EXTRA_CFLAGS="-O0 -ggdb" DEBUG=1 -j4
